name = atl_server_filter
title = Messages Filter
description = This mod allows you to filter the messages sent in order to maintain calm in your server.
depends = 
optional_depends = 
author = Atlante